Fixed linking bug on Linux.
The linking of shader_test on Linux arch produced this error:
`FAILED: c++ -lX11 -lGL -lGLU -lpthread -o shader_test -Wl,--start-group obj/app/shader_test.main-posix.o obj/app/shader_test.test-shader.o obj/third-party/libglew.a obj/library/library.a -Wl,--end-group  -lGL -lX11
obj/library/render/library.gl-shader-object.o: In function `render::GLShaderObject::Compile(unsigned int)':
/home/petar/src/engine/out/Debug/../../library/render/gl-shader-object.cc:38: undefined reference to `gluErrorString'
collect2: error: ld returned 1 exit status`
-lGLU should be in the end, which is produced by adding -lGLU flag to GLEW.
Note that -lGL and -lGLU are removed from library.gyp because they're redundant as they're cotained in static build of glew.